### ISSUE TITLE
sporttracker in arch

### ISSUE THREAD

**Issue by Monirzadeh** [ssaring/sportstracker#263]
When i try to run sporttracker in arch linux (aur package)
get this error
```
WARNING com.sun.javafx.application.PlatformImpl startup Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3783d7ca' 
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:202)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:200)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Unknown Source)
```

any one can help to resolve this error?
i use wayland.

**Comment by ssaring** [comment]
Do you have an X11 compatibility layer in your Wayland installation?
Due to lack of an Wayland-based system I've never tested how SportsTracker runs on such an environment. Is there anybody with some insights on that?

**Comment by ssaring** [comment]
As said, I don't have any Wayland system to test the compatibilty. Don't know whether JavaFX based applications are running on Wayland at all or whether there some special steps needed. Maybe some other Linux user with Wayland can support here.
